services:
  sut:
    build: .
    command: /test.sh
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - ${PWD}/test/test.sh:/test.sh

  namenode:
    image: jaconi/hadoop:latest-hadoop3.3.0
    command: hdfs namenode
    environment:
      FS_DEFAULTFS: hdfs://namenode:9000
    depends_on:
      - namenode-format
    volumes:
      - namenode:/tmp/hadoop-root/dfs/name

  namenode-format:
    image: jaconi/hadoop:latest-hadoop3.3.0
    command: hdfs namenode -format -nonInteractive
    environment:
      FS_DEFAULTFS: hdfs://namenode:9000
    volumes:
      - namenode:/tmp/hadoop-root/dfs/name

  datanode1:
    image: jaconi/hadoop:latest-hadoop3.3.0
    command: hdfs datanode
    environment:
      FS_DEFAULTFS: hdfs://namenode:9000
    volumes:
      - datanode1:/tmp/hadoop-root/dfs/name

  datanode2:
    image: jaconi/hadoop:latest-hadoop3.3.0
    command: hdfs datanode
    environment:
      FS_DEFAULTFS: hdfs://namenode:9000
    volumes:
      - datanode2:/tmp/hadoop-root/dfs/name

volumes:
  namenode:
  datanode1:
  datanode2:
